<?php
// Conexão com o banco de dados Oracle
$usuario = "tasy";
$senha = "haoc_teste"; 
$banco_de_dados = '(DESCRIPTION=
      (ADDRESS=
        (PROTOCOL=TCP)
        (HOST=scan-dbhtml5.oswaldocruz.intranet)
        (PORT=1521))
      (CONNECT_DATA=
        (SERVER=DEDICATED)
        (SERVICE_NAME=dbhtml5.oswaldocruz.intranet)
        (FAILOVER_MODE=
          (TYPE=select)
          (METHOD=basic) ) ) )';

$conn = oci_connect($usuario, $senha, $banco_de_dados);

if (!$conn) {
    $erro = oci_error();
    echo "Falha na conexão: " . $erro['message'];
    exit();
}

// Verificar se é uma solicitação GET
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Query para selecionar todos os registros da tabela exemplo
/*     $query = "SELECT 
ds_convenio as ".'"title"'.",
'rowId '||rownum ".'"rowId"'."
FROM convenio where cd_convenio in (267,340,733,136,1327)"; */

$query = "SELECT 
ds_convenio as ".'"title"'.",
cd_convenio as ".'"rowId"'." 
FROM convenio where cd_convenio in (267,340,733,136,1327)"; 
    
    // Preparar a query
    $stmt = oci_parse($conn, $query);
    
    // Executar a query
    oci_execute($stmt);

    // Array para armazenar os resultados da consulta
     $resultados = array(); 

    // Loop através dos resultados da consulta
     while ($row = oci_fetch_assoc($stmt)) {
        $resultados[] = $row;
    } 
	
	// Loop através dos resultados e imprime na tela
	$remoteJid = $_GET["remoteJid"];
	
	$json_resultados = array(
    "number" => $remoteJid,
    "options" => array(
        "delay" => 1200,
        "presence" => "composing"
    ),
    "listMessage" => array(
        "title" => "Selecione seu convênio",
        "description" => "Você vai poder selecionar seu convênio na lista a seguir",
        "buttonText" => "Clique Aqui!",
        "sections" => array(
            array(
                "title" => "Opções",
                "rows" => $resultados
            )
        )
    )
);



    // Retornar os resultados como JSON
    header('Content-Type: application/json');
	
	$json_response = json_encode($json_resultados);
   // echo json_encode($json_resultados);


 }else {
    // Se não for uma solicitação GET, retornar um erro
    header("HTTP/1.1 405 Method Not Allowed");
	
    echo json_encode(array("message" => "Método não permitido"));
} 

  
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
  $ch = curl_init();

 curl_setopt($ch, CURLOPT_URL, 'https://apistepfy.agencia283.com.br/message/sendList/Stepfy');
 curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
 curl_setopt($ch, CURLOPT_POST, 1);


 curl_setopt($ch, CURLOPT_POSTFIELDS,$json_response);


 $headers = array();
 $headers[] = 'Accept: application/json';
 $headers[] = 'Apikey: bg7WjFAJp7MeT4xmFwWk';
 $headers[] = 'Content-Type: application/json';
 curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

 $result = curl_exec($ch);
 if (curl_errno($ch)) {
     echo 'Error:' . curl_error($ch);
 }
 curl_close($ch);  
  
//echo "<script>alert('$result');</script>"; */
// Fechar conexão com o banco de dados
oci_close($conn);


?>