<?php
// Conexão com o banco de dados Oracle
$usuario = "tasy";
$senha = "haoc_teste"; 
$banco_de_dados = '(DESCRIPTION=
      (ADDRESS=
        (PROTOCOL=TCP)
        (HOST=scan-dbhtml5.oswaldocruz.intranet)
        (PORT=1521))
      (CONNECT_DATA=
        (SERVER=DEDICATED)
        (SERVICE_NAME=dbhtml5.oswaldocruz.intranet)
        (FAILOVER_MODE=
          (TYPE=select)
          (METHOD=basic) ) ) )';

$conn = oci_connect($usuario, $senha, $banco_de_dados);

if (!$conn) {
    $erro = oci_error();
    echo "Falha na conexão: " . $erro['message'];
    exit();
}

// Verificar se é uma solicitação GET
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Query para selecionar todos os registros da tabela exemplo


$query = "select

'%PDF-1.4
%צה
1 0 obj
<</Type /Catalog/Pages 2 0 R>>
endobj
2 0 obj

<</Type /Pages/Kids [3 0 R]/Count 1>>
endobj
3 0 obj
<</Type /Page/MediaBox [0 0 612 792]/Parent 2 0 R/Resources 4 0 R/Contents 5 0 R>>
endobj
4 0 obj
<</ProcSet [/PDF]/Font 6 0 R>>
endobj
5 0 obj
<</Length 7 0 R>>
stream '||
'
BT
/F0 12 Tf
100 680 Td
16 TL
ET

BT
/F0 12 Tf
100 700 Td
(Paciente:'||nr_interno_conta||') Tj T*
'||(select listagg('(contas: '||nr_interno_conta||') Tj T*',' ') campo
                from conta_paciente where nr_interno_conta in (12338,12339))||' 
16 TL
ET '
||
'endstream
endobj
6 0 obj
<</F0 8 0 R>>
endobj
7 0 obj
51
endobj
8 0 obj
<</Type /Font/Subtype /Type1/BaseFont /Helvetica>>
endobj
xref
0 8
0000000000 65535 f
0000000015 00000 n
0000000064 00000 n
0000000121 00000 n
0000000225 00000 n
0000000274 00000 n
0000000372 00000 n
0000000403 00000 n
0000000421 00000 n
trailer
<</Root 1 0 R
/ID [<01234567890ABCDEF> <01234567890ABCDEF>]
/Size 8
>>
startxref
491
%%EOF
'

 campo     
 from conta_paciente where nr_interno_conta = 12338"; 
    
    // Preparar a query
    $stmt = oci_parse($conn, $query);
    
    // Executar a query
    oci_execute($stmt);

    // Array para armazenar os resultados da consulta
     $resultados = array(); 
		
	
	while (($row = oci_fetch_array($stmt, OCI_ASSOC)) != false) {
    // Imprime o valor do campo
    $resultados = $row['CAMPO'];
	$result_encode = base64_encode($resultados);  
	
	ECHO $result_encode ;
}
	// Loop através dos resultados e imprime na tela
	//$remoteJid = $_GET["remoteJid"];

	
	$json_resultados = array(
    "number" => "5591980643660",
    "options" => array(
        "delay" => 1200,
        "presence" => "composing"
    ),
    "mediaMessage" => array(
        "mediatype" => "document",
        "fileName" => "relatorio.pdf",
        "caption" => "Clique Aqui!",
        "media" => $result_encode

        
    )
);



    // Retornar os resultados como JSON
    header('Content-Type: application/json');
	
	$json_response = json_encode($json_resultados);
 echo json_encode($json_resultados);

 }else {
    // Se não for uma solicitação GET, retornar um erro
    header("HTTP/1.1 405 Method Not Allowed");
	
    echo json_encode(array("message" => "Método não permitido"));
} 

  
 // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
  $ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://apistepfy.agencia283.com.br/message/sendMedia/Stepfy');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS,$json_response);

$headers = array();
$headers[] = 'Accept: application/json';
$headers[] = 'Apikey: bg7WjFAJp7MeT4xmFwWk';
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch); 
  
ECHO $result; 
// Fechar conexão com o banco de dados
oci_close($conn);


?>